name: intrinsic

config-version: 2

profile: intrinsic

models:
  intrinsic:
    +meta:
      dagster:
        group: silver
        auto_materialize_policy:
          type: eager
    marts:
      +materialized: table
      +schema: analytics
      +meta:
        dagster:
          group: gold
          auto_materialize_policy:
            type: eager
    staging:
      +schema: staging
