name: intrinsic

config-version: 2

profile: intrinsic

models:
  intrinsic:
    marts:
      +materialized: table
      +schema: analytics
    intermediate:
      +schema: intermediate
    staging:
      +schema: staging
seeds:
  intrinsic:
    +schema: seeds
