name: intrinsic

config-version: 2

profile: intrinsic

vars:
  risk_free_rate: 0.1401
  terminal_growth_rate: 0.0378

models:
  intrinsic:
    marts:
      +materialized: table
      +schema: analytics
    intermediate:
      +schema: intermediate
    staging:
      +schema: staging
seeds:
  intrinsic:
    +schema: seeds
