name: intrinsic

config-version: 2

profile: intrinsic

vars:
  risk_free_rate: 0.1235
  terminal_growth_rate: 0.0727
  transient_period: 7

models:
  intrinsic:
    +meta:
      dagster:
        group: silver
        auto_materialize_policy:
          type: eager
    marts:
      +materialized: table
      +schema: analytics
      +meta:
        dagster:
          group: gold
          auto_materialize_policy:
            type: eager
    intermediate:
      +schema: intermediate
    staging:
      +schema: staging
seeds:
  intrinsic:
    +schema: seeds
    +meta:
      dagster:
        group: bronze
        auto_materialize_policy:
          type: eager
