name: intrinsic

config-version: 2

profile: intrinsic

vars:
  gov_bond_rate: 0.1395

models:
  intrinsic:
    marts:
      +materialized: table
      +schema: analytics
    intermediate:
      +schema: intermediate
    staging:
      +schema: staging
seeds:
  intrinsic:
    +schema: seeds
