version: 2

seeds:
  - name: industry_translation
    description: A mapping of Brazilian industry names to their English counterparts.
    config:
      delimiter: ;
    columns:
      - name: industry_pt
        description: The Brazilian name of the industry
        tests:
          - unique
          - not_null
      - name: industry_en
        description: The English name of the industry
        tests:
          - unique
          - not_null
