name: Ingest Balance Sheets

on:
  workflow_dispatch:

jobs:
  ingest-balance-sheets:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install --system -r requirements.txt

      - name: Ingest balance sheets
        env:
          SOURCES__FILESYSTEM_PIPELINE__BUCKET_URL: ${{ vars.FUNDAMENTUS_BUCKET }}
          SOURCES__FILESYSTEM_PIPELINE__CREDENTIALS__AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SOURCES__FILESYSTEM_PIPELINE__CREDENTIALS__AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCES__FILESYSTEM_PIPELINE__CREDENTIALS__REGION_NAME: ${{ secrets.AWS_REGION }}
          DESTINATION__MOTHERDUCK__CREDENTIALS__DATABASE: ${{ secrets.MOTHERDUCK_DATABASE }}
          DESTINATION__MOTHERDUCK__CREDENTIALS__PASSWORD: ${{ secrets.MOTHERDUCK_TOKEN }}
        run: |
          cd ingestion && python filesystem_pipeline.py
