name: Serverless Branch Deployments
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths-ignore: [ ".github/workflows/aws.yml", ".github/workflows/deploy.yml", "app/**"  ]

concurrency:
  # Cancel in-progress deploys to same branch
  group: ${{ github.ref }}/branch_deployments
  cancel-in-progress: true
env:
  DAGSTER_CLOUD_URL: "http://datavillas.dagster.plus"
  ORGANIZATION_ID: datavillas
  DAGSTER_CLOUD_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
  ENABLE_FAST_DEPLOYS: 'true'
  PYTHON_VERSION: '3.12'
  DAGSTER_CLOUD_FILE: 'dagster_cloud.yaml'
  GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
  DBT_TARGET_PATH: transformation/target
  DBT_MANIFEST_S3_BUCKET: intrinsic-value-dbt-manifests
  DBT_MANIFEST_S3_PREFIX: ${{ github.event.action == 'opened' && 'main' || github.head_ref }}

jobs:
  dagster_cloud_default_deploy:
    name: Dagster Serverless Deploy
    runs-on: ubuntu-22.04
    outputs:
      build_info: ${{ steps.parse-workspace.outputs.build_info }}

    steps:
      - name: Prerun Checks
        id: prerun
        uses: dagster-io/dagster-cloud-action/actions/utils/prerun@v0.1

      - name: Launch Docker Deploy
        if: steps.prerun.outputs.result == 'docker-deploy'
        id: parse-workspace
        uses: dagster-io/dagster-cloud-action/actions/utils/parse_workspace@v0.1
        with:
          dagster_cloud_file: $DAGSTER_CLOUD_FILE

      - name: Checkout for Python Executable Deploy
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref}}

      - name: Set up Python and cache dependencies
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
        
      - name: Install Python dependencies
        run: |
          python -m pip install pip --upgrade
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

        
      - name: Download manifest
        run: |
          mkdir -p "${{ env.DBT_TARGET_PATH }}"
          aws s3 cp "s3://${{ env.DBT_MANIFEST_S3_BUCKET }}/${{ env.DBT_MANIFEST_S3_PREFIX }}/manifest.json" "${{ env.DBT_TARGET_PATH }}/manifest.json"

      - name: Prepare dbt project for deployment
        run: |
          dagster-dbt project prepare-and-package --file orchestration/defs/transformation.py
      
      - name: Upload manifest artifact
        run: |
          aws s3 cp "${{ env.DBT_TARGET_PATH }}/manifest.json" "s3://${{ env.DBT_MANIFEST_S3_BUCKET }}/${{ github.head_ref }}/manifest.json"

      - name: Python Executable Deploy
        if: steps.prerun.outputs.result == 'pex-deploy'
        uses: dagster-io/dagster-cloud-action/actions/build_deploy_python_executable@v0.1
        with:
          dagster_cloud_file: "$GITHUB_WORKSPACE/$DAGSTER_CLOUD_FILE"
          build_output_dir: "$GITHUB_WORKSPACE/build"
          python_version: "${{ env.PYTHON_VERSION }}"
      
      - name: Get branch deployment
        id: branch-deployment
        if: github.event.action != 'synchronize'
        uses: dagster-io/dagster-cloud-action/actions/utils/get_branch_deployment@v0.1
        with:
          dagster_cloud_url: ${{ env.DAGSTER_CLOUD_URL }}
       
      
      - name: Clone Motherduck database upon launch
        if: github.event.action == 'opened' || github.event.action == 'reopened'
        uses: dagster-io/dagster-cloud-action/actions/utils/run@v0.1
        with:
          location_name: intrinsic-value
          deployment: ${{ steps.branch-deployment.outputs.deployment }}
          job_name: clone_prod
          
      - name: Delete Motherduck db clone upon PR close
        if: github.event.action == 'closed'
        uses: dagster-io/dagster-cloud-action/actions/utils/run@v0.1
        with:
          location_name: intrinsic-value
          deployment: ${{ steps.branch-deployment.outputs.deployment }}
          job_name: drop_prod_clone

  dagster_cloud_docker_deploy:
    name: Docker Deploy
    runs-on: ubuntu-20.04
    if: needs.dagster_cloud_default_deploy.outputs.build_info
    needs: dagster_cloud_default_deploy
    strategy:
      fail-fast: false
      matrix:
        location: ${{ fromJSON(needs.dagster_cloud_default_deploy.outputs.build_info) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Build and deploy to Dagster Cloud serverless
        uses: dagster-io/dagster-cloud-action/actions/serverless_branch_deploy@v0.1
        with:
          dagster_cloud_api_token: ${{ env.DAGSTER_CLOUD_API_TOKEN }}
          location: ${{ toJson(matrix.location) }}
          base_image: "python:${{ env.PYTHON_VERSION }}-slim"
          organization_id: ${{ env.ORGANIZATION_ID }}
