name: Serverless Prod Deployment
on:
  push:
    branches:
      - "main"
      - "master"

concurrency:
  # Cancel in-progress deploys to same branch
  group: ${{ github.ref }}/deploy
  cancel-in-progress: true
env:
  DAGSTER_CLOUD_URL: "http://datavillas.dagster.plus"
  DAGSTER_CLOUD_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
  ORGANIZATION_ID: "datavillas"
  ENABLE_FAST_DEPLOYS: 'true'
  PYTHON_VERSION: '3.12'
  DAGSTER_CLOUD_FILE: 'dagster_cloud.yaml'
  GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
  DBT_TARGET_PATH: transformation/target
  DBT_MANIFEST_S3_BUCKET: intrinsic-value-dbt-manifests
 
jobs:
  dagster_cloud_default_deploy:
    name: Dagster Serverless Deploy
    runs-on: ubuntu-22.04
    outputs:
      build_info: ${{ steps.parse-workspace.outputs.build_info }}

    steps:
      - name: Prerun Checks
        id: prerun
        uses: dagster-io/dagster-cloud-action/actions/utils/prerun@v0.1

      - name: Launch Docker Deploy
        if: steps.prerun.outputs.result == 'docker-deploy'
        id: parse-workspace
        uses: dagster-io/dagster-cloud-action/actions/utils/parse_workspace@v0.1
        with:
          dagster_cloud_file: $DAGSTER_CLOUD_FILE

      - name: Checkout for Python Executable Deploy
        if: steps.prerun.outputs.result == 'pex-deploy'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      

      
      - name: Set up Python and cache dependencies
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
        
      - name: Install Python dependencies
        run: |
          python -m pip install pip --upgrade
          pip install -r requirements.txt

      - name: Download manifest to tmp # to overcome permission issues
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: "s3://${{ env.DBT_MANIFEST_S3_BUCKET }}/${{ github.head_ref }}/manifest.json"
          destination: "/tmp/manifest.json"
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
      
      - name: Copy manifest to expected location # to overcome permission issues
        run: |
          mkdir -p $DBT_TARGET_PATH
          cp /tmp/manifest.json ${DBT_TARGET_PATH}/manifest.json

      - name: Prepare dbt project for deployment
        id: prepare-dbt
        run: |
          if [[ ! -f "./transformation/target/manifest.json" ]]; then
            echo "Compiling DBT because manifest is missing"
            cd transformation
            dbt deps
            dbt compile
            cd ..
            echo "compiled=true" >> $GITHUB_OUTPUT
          else
            echo "Using cached manifest"
            echo "compiled=false" >> $GITHUB_OUTPUT
          fi
          dagster-dbt project prepare-and-package --file orchestration/defs/transformation.py
      
      - name: Upload manifest artifact
        if: steps.prepare-dbt.outputs.compiled == 'true'
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: "${{ env.DBT_TARGET_PATH }}/manifest.json"
          destination: "s3://${{ env.DBT_MANIFEST_S3_BUCKET }}/${{ github.ref_name }}/manifest.json"
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1

      - name: Python Executable Deploy
        if: steps.prerun.outputs.result == 'pex-deploy'
        uses: dagster-io/dagster-cloud-action/actions/build_deploy_python_executable@v0.1
        with:
          dagster_cloud_file: "$GITHUB_WORKSPACE/$DAGSTER_CLOUD_FILE"
          build_output_dir: "$GITHUB_WORKSPACE/build"
          python_version: "${{ env.PYTHON_VERSION }}"

  dagster_cloud_docker_deploy:
    name: Docker Deploy
    runs-on: ubuntu-20.04
    if: needs.dagster_cloud_default_deploy.outputs.build_info
    needs: dagster_cloud_default_deploy
    strategy:
      fail-fast: false
      matrix:
        location: ${{ fromJSON(needs.dagster_cloud_default_deploy.outputs.build_info) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - name: Build and deploy to Dagster Cloud serverless
        uses: dagster-io/dagster-cloud-action/actions/serverless_prod_deploy@v0.1
        with:
          dagster_cloud_api_token: ${{ env.DAGSTER_CLOUD_API_TOKEN }}
          location: ${{ toJson(matrix.location) }}
          base_image: "python:${{ env.PYTHON_VERSION }}-slim"
          organization_id: ${{ env.ORGANIZATION_ID }}
