name: Prepare Analytics Data

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Ingest Balance Sheets
      - Ingest Closing Market Data
    types:
      - completed
  push:
    paths:
      - 'transformation/dbt_project.yml'
      - 'transformation/macros/compute_intrinsic_value.sql'

jobs:
  prepare-analytics:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install --system -r requirements.txt

      - name: Prepare analytics data
        env:
          MOTHERDUCK_DATABASE: ${{ secrets.MOTHERDUCK_DATABASE }}
          MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
        run: |
          cd transformation && dbt build
